apiVersion: v1
kind: Service
metadata: {name: snuh-patient-calculator, labels: {app: snuh-patient-calculator}}
spec:
  selector: {app: snuh-patient-calculator}
  ports: [{port: 8000, targetPort: 8000}]
